### PR TITLE
#161 - Make providers larger on hover 

### LINKED ISSUE #161: Make providers larger on hover
Better visibility of provider icon for user 
Screenshot from 2023-10-25 13-03-08

### PR DESCRIPTION
**Pull request by zmigrOO**
This should close #161

### CODE REVIEW

**Review by Lee0z — APPROVED** [review]

**Comment by AleksandraKozubal** [comment]
When logo is close to the border of the occupied area and I hover it, then the maximized logo does not fit and its edge is cut off

Example below with voi.
image

**Review by AleksandraKozubal — CHANGES_REQUESTED** [review]
When logo is close to the border of the occupied area and I hover it, then the maximized logo does not fit and its edge is cut off

Example below with voi.:
image

**Review by AleksandraKozubal — CHANGES_REQUESTED** [review]
Please add logo maximization in administration panel > cities. It would be useful here too.

**Review by EwelinaSkrzypacz — COMMENTED** [review]
1. Please fix GitHub warnings

image


2. I'm not a big fan of making larger icons on hover. Wy we can't just make bigger icons? And how on mobile I can hover on icons?

**Comment by zmigrOO** [comment]
>     2. I'm not a big fan of making larger icons on hover. Wy we can't just make bigger icons? And how on mobile I can hover on icons?

I think larger icons may not fit properly, and I still have to figure out what to do with it on mobile. We can just make them bigger for users, but for admin panel I would leave it with hover effect to have more compressed layout.

**Comment by EwelinaSkrzypacz** [comment]
> > ```
> > 2. I'm not a big fan of making larger icons on hover. Wy we can't just make bigger icons? And how on mobile I can hover on icons?
> > ```
> 
> I think larger icons may not fit properly, and I still have to figure out what to do with it on mobile. We can just make them bigger for users, but for admin panel I would leave it with hover effect to have more compressed layout.

I think I will try to make bigger icon on admin panel. Maybe if we have for example three providers, we should show icons, but if more, just show number of providers? Like we have now on mobile? I really want to avoid hovering on things like that.

**Comment by zmigrOO** [comment]
> > > ```
> > > 2. I'm not a big fan of making larger icons on hover. Wy we can't just make bigger icons? And how on mobile I can hover on icons?
> > > ```
> > 
> > I think larger icons may not fit properly, and I still have to figure out what to do with it on mobile. We can just make them bigger for users, but for admin panel I would leave it with hover effect to have more compressed layout.
> 
> I think I will try to make bigger icon on admin panel. Maybe if we have for example three providers, we should show icons, but if more, just show number of providers? Like we have now on mobile? I really want to avoid hovering on things like that.

I'll just try making them bigger and see how it comes out

**Review by EwelinaSkrzypacz — COMMENTED** [review]
I think it's beeter, but I will get rid of borders - it looks better

image

**Comment by zmigrOO** [comment]
image
there is also a problem when there's only one provider in the city, I'll try to fix it too

**Review by AleksandraKozubal — APPROVED** [review]

**Review by EwelinaSkrzypacz — APPROVED** [review]

**Pull request merged**
