### PR TITLE
#142 - Add Hopp provider

### LINKED ISSUE #142: Add Hopp provider
* go to https://hopp.bike/locations
* scrap multiple locations including 25 cities in Iceland (!) and Zgorzelec (!!)

obraz

### PR DESCRIPTION
**Pull request by JakubKermes**
This should close #142

### CODE REVIEW

**Review by AleksandraKozubal — COMMENTED** [review]
image
The same thing happens here as in WheeMove, please add comment in #86 about it

**Comment by kamilpiech97** [comment]
@JakubKermes please add description for your PR.

**Review by EwelinaSkrzypacz — COMMENTED** [review]
wip

**Comment by EwelinaSkrzypacz** [comment]
> Why I have 57 location on the list, but on admin home page (statistics) I see that I have only 54?

As I observe, the problem occurs in almost all providers, co I think we should make separate issue for that. @JakubKermes  can you verify that this problem occurs and if so, create the issue?

**Comment by JakubKermes** [comment]
@EwelinaSkrzypacz This issue occurs in almost all providers. Ryde shows 14 locations in the dashboard, but on the website, it has 25. Hulaj shows the correct number of 2 locations. Discrepancy seems to be present only in the dashboard, as there is the correct number of locations displayed on the map.

**Review by EwelinaSkrzypacz — APPROVED** [review]

**Review by AleksandraKozubal — APPROVED** [review]

**Pull request merged**
